[package]
description = "A simple parser and serializer for Scoop shims"
edition = "2021"
include = ["src", "README.md", "LICENSE", "tests"]
license = "Apache-2.0"
name = "scoop-shim"
repository = "https://github.com/winpax/scoop-shim/tree/trunk"
version = "0.1.0"

[dependencies]
thiserror = "1.0"
